force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(
ISBLANK(Primary_Contact__c),
&quot;&quot;,
Primary_Contact__r.Email
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Original_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Original_Entity_Type__c</fullName>
    <label>Original Entity Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Primary_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/State_of_Business__c.field-meta.xml
<CustomField>
    <fullName>State_of_Business__c</fullName>
    <label>State of Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Calc_Discount_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Calc_Discount_Code__c</fullName>
    <label>Tax Calculator Discount Code</label>
    <length>244</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Calculator_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_Calculator_ID__c</fullName>
    <label>Tax Calculator ID</label>
    <length>244</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connection_Settings__c/Connection_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to hold Django connection settings</description>
    <label>Connection Settings</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LLC -&gt; SC</fullName>
            </value>
            <value>
                <fullName>SP -&gt; SC</fullName>
            </value>
            <value>
                <fullName>Remain SC</fullName>
            </value>
            <value>
                <fullName>Remain C-Corp SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <description>This field will replace Profession field that&apos;s under Activity object. It will be used in the new sales flow</description>
    <label>Profession</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(
NOT(ISNULL(Primary_Contact__c)),
Primary_Contact__r.Email,
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LLC -&gt; SC</fullName>
            </value>
            <value>
                <fullName>SP -&gt; SC</fullName>
            </value>
            <value>
                <fullName>Remain SC</fullName>
            </value>
            <value>
                <fullName>Remain C-Corp SC</fullName>
            </value>
            <value>
                <fullName>C-Corp</fullName>
                <isActive>false</isActive>
                <label>C-Corp</label>
            </value>
            <value>
                <fullName>New -&gt; SC</fullName>
                <isActive>false</isActive>
                <label>New -&gt; SC</label>
            </value>
            <value>
                <fullName>Remain LLC</fullName>
                <isActive>false</isActive>
                <label>Remain LLC</label>
            </value>
            <value>
                <fullName>SP -&gt; LLC</fullName>
                <isActive>false</isActive>
                <label>SP -&gt; LLC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Primary_Opp_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Signup_Link__c.field-meta.xml
<CustomField>
    <fullName>Signup_Link__c</fullName>
    <description>This field is populated through Acquisition Form Callout</description>
    <label>Signup Link</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GenerateNewSignupLinkCallout.cls
public without sharing class GenerateNewSignupLinkCallout {
    
    @AuraEnabled 
    public static String InvokeNewSignupLinkEndpoint(String memberId){
        Opportunity opp = [Select id, Email__c, Plan__c, LeadSource, Signup_Link__c, OwnerId, AccountId from Opportunity where Id =: memberId];
        System.debug('Opportunity: ' + opp);
        Account acc = [Select id, Email__c, Name, Original_Entity_Type__c, State_of_Business__c, Primary_Contact__c, Tax_Calc_Discount_Code__c, Tax_Calculator_ID__c from Account where Id =: opp.AccountId];
        System.debug('Account: ' + acc);
        Contact cntc = [Select Id, Email, FirstName, LastName, Secondary_Email__c, Profession__c from Contact where Id =: acc.Primary_Contact__c];
        System.debug('Contact: ' + cntc);
        User usr = [Select Id, Name from User where Id =: opp.OwnerId];
        System.debug('User: ' + usr);
        Connection_Settings__c acqFormAuth = Connection_Settings__c.getValues('AcquisitionFormRequest');
        String memberEmail = opp.Email__c;
        System.debug('memberEmail: ' + memberEmail);
        Http h = new Http();
        
        
        AcquisitionFormRequestBody.acquisitionFormClaims acquisitionFormData = new AcquisitionFormRequestBody.acquisitionFormClaims();
        acquisitionFormData.MemberFirstName = cntc.FirstName;
        acquisitionFormData.MemberLastName = cntc.LastName;
        acquisitionFormData.PrimaryEmailAddress = cntc.Email;
        acquisitionFormData.EntityType = opp.Plan__c;
        acquisitionFormData.State = acc.State_of_Business__c;
        acquisitionFormData.LeadSource = opp.LeadSource;
        acquisitionFormData.AssignedToID = opp.OwnerId;
        acquisitionFormData.AssignedToName = usr.Name;
        acquisitionFormData.TaxCalcID = acc.Tax_Calculator_ID__c;
        acquisitionFormData.SFDCcontactID = cntc.Id;
        acquisitionFormData.SFDCaccountID = acc.Id;
        acquisitionFormData.SFDCPrimaryOppID = opp.Id;
        acquisitionFormData.DiscountCode = acc.Tax_Calc_Discount_Code__c;
        acquisitionFormData.Profession = cntc.Profession__c;
        System.debug('acquisitionFormData: ' + acquisitionFormData);
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(acqFormAuth.Url__c);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
		req.setHeader('Accept', 'application/json');        
        req.setHeader('Authorization', 'Token ' + acqFormAuth.Token__c);   
        
        AcquisitionFormRequestBody acquisitionFullRequest = new AcquisitionFormRequestBody();
        acquisitionFullRequest.email = acquisitionFormData.PrimaryEmailAddress;
        acquisitionFullRequest.claims = acquisitionFormData;    
        System.debug('acquisitionFullRequest: ' + acquisitionFullRequest);
        req.setBody(acquisitionFullRequest.stringify());       
        System.debug('request: ' + req);
        String strResponse = null;     
        String finalUrl = null;
        String error = null;
        
        try{
            HttpResponse res = h.send(req);
            AcquisitionFormResponseBody formatResponse = new AcquisitionFormResponseBody();
            System.debug('response final: ' + res.getBody());
            if(res.getStatusCode() == 201){
                formatResponse = (AcquisitionFormResponseBody) JSON.deserialize(res.getBody(), AcquisitionFormResponseBody.class);
                finalUrl = formatResponse.frontend_url;
                strResponse = res.getBody();
            } else {
                strResponse = 'SignupLink with this email already exists';
            }
        } catch(Exception ex){
            throw ex; 
        }
        
        System.debug('strResponse: ' + strResponse);
        System.debug('finalUrl: ' + finalUrl);
        
        if(!String.isBlank(finalUrl)){
            opp.Signup_Link__c = finalUrl;                
            update opp;                        
            return strResponse;
        } else {
            return strResponse;
        }
    }
    
    public class RegenerateSignupLinkRequestBody{
        public string email;
    }    
        
    public class AcquisitionFormResponseBody{
        public string email;
        public string frontend_url;
        public string backend_url;
        public string token;
    }    
}