force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(
ISBLANK(Primary_Contact__c),
&quot;&quot;,
Primary_Contact__r.Email
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Original_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Original_Entity_Type__c</fullName>
    <label>Original Entity Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State_of_Business__c.field-meta.xml
<CustomField>
    <fullName>State_of_Business__c</fullName>
    <label>State of Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Calc_Discount_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Calc_Discount_Code__c</fullName>
    <label>Tax Calculator Discount Code</label>
    <length>244</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Calculator_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_Calculator_ID__c</fullName>
    <label>Tax Calculator ID</label>
    <length>244</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connection_Settings__c/Connection_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to hold Django connection settings</description>
    <label>Connection Settings</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LLC -&gt; SC</fullName>
            </value>
            <value>
                <fullName>SP -&gt; SC</fullName>
            </value>
            <value>
                <fullName>Remain SC</fullName>
            </value>
            <value>
                <fullName>Remain C-Corp SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(
NOT(ISNULL(Primary_Contact__c)),
Primary_Contact__r.Email,
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LLC -&gt; SC</fullName>
            </value>
            <value>
                <fullName>SP -&gt; SC</fullName>
            </value>
            <value>
                <fullName>Remain SC</fullName>
            </value>
            <value>
                <fullName>Remain C-Corp SC</fullName>
            </value>
            <value>
                <fullName>C-Corp</fullName>
                <isActive>false</isActive>
                <label>C-Corp</label>
            </value>
            <value>
                <fullName>New -&gt; SC</fullName>
                <isActive>false</isActive>
                <label>New -&gt; SC</label>
            </value>
            <value>
                <fullName>Remain LLC</fullName>
                <isActive>false</isActive>
                <label>Remain LLC</label>
            </value>
            <value>
                <fullName>SP -&gt; LLC</fullName>
                <isActive>false</isActive>
                <label>SP -&gt; LLC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RegenerateSignupLinkCallout_Test.cls
@isTest
public class RegenerateSignupLinkCallout_Test {
    Private Static Final String ACCOUNT_NAME = 'Test Acc';
    Private Static Final String MEMBER_EMAIL = 'itslukestonetest@gmail.com';
    
    @testSetup static void setupData() {
        Account testAccount = New Account(Name = ACCOUNT_NAME, State_of_Business__c = 'California', Original_Entity_Type__c = 'SP -> SC', Tax_Calc_Discount_Code__c = 'ABCDEF0', Tax_Calculator_ID__c = '123456');
        insert testAccount;                          
        
        Contact testContact = New Contact(AccountId = testAccount.Id, FirstName = 'Test', LastName = 'Account', Email = MEMBER_EMAIL, Secondary_Email__c = 'testAccount1234@testing.net');
        insert testContact;
        
        Opportunity testOpportunity = [SELECT Id, Email__c FROM Opportunity WHERE AccountId =: testAccount.Id LIMIT 1];     
        testOpportunity.Plan__c = Opportunity.Plan__c.getDescribe().getPicklistValues()[0].getValue();
        update testOpportunity;       
        
        Connection_Settings__c cs = new Connection_Settings__c();
        cs.Name = 'AcquisitionFormRequest';
        cs.url__c = 'https://somefakeurl.net';
        cs.Token__c = '432kr32jhk3k2j432kjh4';        
        insert cs;            
        system.debug('11135');
    }         
    
    private class MockOk implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setStatus('OK');
            res.setStatusCode(200);
            res.setBody('{"email": "ewewewe@collective.com","frontend_url": "https://collective.heroku.com/signup-link/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9","backend_url":"https://collective.com/","token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9"}');
            return res;
        }
    }
    
    private class MockError implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setStatus('Bad Request');
            res.setStatusCode(400);
            res.setBody('{"error": "Unable to find existing signup link for this member"}');
            return res;
        }
    }        
    
    @isTest static void InvokeSignupLinkEndpoint() {
        Test.startTest();
        
        Account acct = [SELECT Id, Name, Tax_Calc_Discount_Code__c, State_of_Business__c, Tax_Calculator_ID__c FROM Account WHERE Name=: ACCOUNT_NAME LIMIT 1];
        System.debug('acct: ' + acct);
        Opportunity oppt = [SELECT Id, Email__c FROM Opportunity WHERE AccountId =: acct.Id];
        System.debug('oppt: ' + oppt);        
        
        Test.setMock(HttpCalloutMock.class, new MockOk());
        String response;        
        response = RegenerateSignupLinkCallout.InvokeSignupLinkEndpoint(oppt.Id);
        System.assertNotEquals('{"error": "Unable to find existing signup link for this member"}', response);
     
        Test.stopTest();
        
    }    
    
    @isTest static void InvokeSignupLinkEndpointError() {
        Test.startTest();
        
        Account acct = [SELECT Id, Name, Tax_Calc_Discount_Code__c, State_of_Business__c, Tax_Calculator_ID__c FROM Account WHERE Name=: ACCOUNT_NAME LIMIT 1];
        System.debug('acct: ' + acct);
        Opportunity oppt = [SELECT Id, Email__c FROM Opportunity WHERE AccountId =: acct.Id];
        System.debug('oppt: ' + oppt);        
        
        String response;  
        Test.setMock(HttpCalloutMock.class, new MockError());
        response = RegenerateSignupLinkCallout.InvokeSignupLinkEndpoint(oppt.Id);
        System.assertEquals('{"error": "Unable to find existing signup link for this member"}', response);    
        Test.stopTest();
        
    }    
        
    

}