force-app/main/default/objects/Account/fields/Original_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Original_Entity_Type__c</fullName>
    <label>Original Entity Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State_of_Business__c.field-meta.xml
<CustomField>
    <fullName>State_of_Business__c</fullName>
    <label>State of Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Calc_Discount_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Calc_Discount_Code__c</fullName>
    <label>Tax Calculator Discount Code</label>
    <length>244</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Calculator_ID__c.field-meta.xml
<CustomField>
    <fullName>Tax_Calculator_ID__c</fullName>
    <label>Tax Calculator ID</label>
    <length>244</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connection_Settings__c/Connection_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to hold Django connection settings</description>
    <label>Connection Settings</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LLC -&gt; SC</fullName>
            </value>
            <value>
                <fullName>SP -&gt; SC</fullName>
            </value>
            <value>
                <fullName>Remain SC</fullName>
            </value>
            <value>
                <fullName>Remain C-Corp SC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DropboxFile__x/DropboxFile__x.object-meta.xml
<CustomObject>
    <description>DropboxFiles</description>
    <externalDataSource>CollectiveBackEnd</externalDataSource>
    <externalName>DropboxFiles</externalName>
    <label>DropboxFile</label>
    <pluralLabel>DropboxFiles</pluralLabel>
</CustomObject>

force-app/main/default/objects/DropboxFile__x/fields/file_id__c.field-meta.xml
<CustomField>
    <fullName>file_id__c</fullName>
    <description>file_id</description>
    <externalDeveloperName>file_id</externalDeveloperName>
    <label>file_id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DropboxFile__x/fields/sfaccountid__c.field-meta.xml
<CustomField>
    <fullName>sfaccountid__c</fullName>
    <description>sfaccountid</description>
    <externalDeveloperName>sfaccountid</externalDeveloperName>
    <label>sfaccountid</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LLC -&gt; SC</fullName>
            </value>
            <value>
                <fullName>SP -&gt; SC</fullName>
            </value>
            <value>
                <fullName>Remain SC</fullName>
            </value>
            <value>
                <fullName>Remain C-Corp SC</fullName>
            </value>
            <value>
                <fullName>C-Corp</fullName>
                <isActive>false</isActive>
                <label>C-Corp</label>
            </value>
            <value>
                <fullName>New -&gt; SC</fullName>
                <isActive>false</isActive>
                <label>New -&gt; SC</label>
            </value>
            <value>
                <fullName>Remain LLC</fullName>
                <isActive>false</isActive>
                <label>Remain LLC</label>
            </value>
            <value>
                <fullName>SP -&gt; LLC</fullName>
                <isActive>false</isActive>
                <label>SP -&gt; LLC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DropboxFileURLCallout_Test.cls
@isTest
public class DropboxFileURLCallout_Test {
    Private Static Final String ACCOUNT_NAME = 'Test Acc';
    Private Static Final String FILE_ID = 'id:zroDv_tp_GAAAAAAAABVGQ';
    
    
    private class MockOk implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setStatus('OK');
            res.setStatusCode(200);
            res.setBody('{"link": "https://www.dropbox.com/s/cgq2s26mpj5kljp/Operating%20Agreement.pdf?dl=0"}');
            return res;
        }
    }
    
    private class MockError implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setStatus('Bad Request');
            res.setStatusCode(400);
            res.setBody('{"error": "Missing required id"}');
            return res;
        }
    }    
    
    @testSetup static void setupData() {
        Account testAccount = New Account(Name = ACCOUNT_NAME, State_of_Business__c = 'California', Original_Entity_Type__c = 'SP -> SC', Tax_Calc_Discount_Code__c = 'ABCDEF0', Tax_Calculator_ID__c = '123456');
        insert testAccount;                          
        
        Contact testContact = New Contact(AccountId = testAccount.Id, FirstName = 'Test', LastName = 'Account', Email = 'testAccount@testing.net', Secondary_Email__c = 'testAccount1234@testing.net');
        insert testContact;
        
        Opportunity testOpportunity = [SELECT Id FROM Opportunity WHERE AccountId =: testAccount.Id LIMIT 1];     
        testOpportunity.Plan__c = Opportunity.Plan__c.getDescribe().getPicklistValues()[0].getValue();
        update testOpportunity;       
        
        /*DropboxFile__x testDropboxFile = New DropboxFile__x(file_id__c = FILE_ID, sfaccountid__c = testAccount.Id, sfopportunityid__c = testOpportunity.Id);
        insertAsync testDropboxFile;                      */
        
        Connection_Settings__c cs = new Connection_Settings__c();
        cs.Name = 'DropboxFileUrl';
        cs.url__c = 'https://somefakeurl.net';
        cs.Token__c = '432kr32jhk3k2j432kjh4';        
        insert cs;            
       
    }    
    
    
    @isTest static void InvokeDropboxURL() {
        Test.startTest();
        
        DropboxFileURLRequestBody reqBody = new DropboxFileURLRequestBody();
        reqBody.file_id = FILE_ID;
        
        Test.setMock(HttpCalloutMock.class, new MockOk());
        String linkUrl;        
        linkUrl = DropboxFileURLCallout.InvokeDropboxURL(FILE_ID);
        System.assertNotEquals(null, linkUrl);
        Test.setMock(HttpCalloutMock.class, new MockError());
        linkUrl = DropboxFileURLCallout.InvokeDropboxURL(FILE_ID);
        System.assertEquals(null, linkUrl);        
        Test.stopTest();
    }
}